name: My First Pipeline
on: push 
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build docker image
        run: docker build -t my-first-image .
 
